name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Qwen3Coder
    provider: vllm
    model: Qwen3Coder
    useLegacyCompletionsEndpoint: true
    apiBase: http://192.168.1.159:19000/v1
    roles:
      - chat
      - autocomplete
context_providers:
  - name: code
  - name: docs
  - name: diff
  - name: terminal
  - name: problems
  - name: folder
  - name: codebase